language: csharp
solution: Dante.sln
mono: none
dotnet: 2.1.802 # LTS
sudo: required

env:
  - CLI_VERSION=latest

jobs:
  include:
    - os: linux
      dist: bionic # Ubuntu 18.04 (LTS)
    - os: osx
      osx_image: xcode11.2 # macOS 10.14 (Mojave)
  allow_failures:
    - os: osx

notifications:
  email:
    - ahadc@maacpiash.com

branches:
  only:
    - master

before_install:
  - if [ $TRAVIS_OS_NAME = ubuntu ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi
  - dotnet --info

script:
  - dotnet restore
  - dotnet build
  